Fix crash due to syntax error
Traceback (most recent call last):
  File "./iotop.py", line 9, in <module>
    from iotop.ui import main
  File "./iotop/ui.py", line 642
    else:
       ^
SyntaxError: invalid syntax

Reported-in: <CAEh_nc0_DXTmfu16PxmVyrCi6QQeSrpnGGhtfNu60wJYfa_6Zw@mail.gmail.com>